INSERT INTO roles(name) VALUES('USER') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES('EDITOR') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES('CREATOR') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES('ADMIN') ON CONFLICT DO NOTHING;